### ISSUE TITLE
Expand betting strategy of all agents (Omen)

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#280] opened 2024-06-26 09:00 UTC
Currently the agents (https://github.com/gnosis/prediction-market-agent-tooling/blob/ceb4304149e94c6f284e1cea38273d0f53dfe37f/prediction_market_agent_tooling/deploy/agent.py#L222) can place N bets on a given market, regardless of how the market is looking like - it only does not do so if market is closed and/or market has no liquidity (https://github.com/gnosis/prediction-market-agent-tooling/blob/ceb4304149e94c6f284e1cea38273d0f53dfe37f/prediction_market_agent_tooling/markets/omen/omen.py#L142).

Also very relevant for placing a bet is the probability with which the market prices the prediction vs the confidence the agent has in the prediction. E.g. if the market prices Trump to win election with 80% and we have a 85% confidence in that prediction, there is payoff P1 ; if instead market prices Trump at 40%, our payoff is P2, and P2 >> P1.
This issue addresses the above logic.

**Comment by kongzii** [comment] 2024-06-26 09:24
Is this the same thing as you meant to do in https://github.com/gnosis/prediction-market-agent/issues/56 ?

**Comment by evangriffiths** [comment] 2024-06-26 11:45
We do have these betting strategies in PMAT that we could give the agent as Tools to choose from

**Comment by evangriffiths** [comment] 2024-09-03 15:33
Closing, as duplicate of https://github.com/gnosis/prediction-market-agent/issues/280

**Comment by kongzii** [comment] 2024-09-19 08:51
This is duplicate of https://github.com/gnosis/prediction-market-agent-tooling/issues/365, right?

**Closed by kongzii** 2024-09-19 08:51 UTC
Labels: all-agents
