### ISSUE TITLE
Think Thoroughly agent - probabilities of mutually-exclusive correlated scenarios should sum up to 1

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#293] opened 2024-07-01 10:27 UTC
See PDF attached
[agent_app_log.pdf](https://github.com/user-attachments/files/16051468/agent_app_log.pdf)
 for an excerpt of an execution of the agent. 

1 - The `SCENARIOS_WITH_PROBABILITIES` contain mutually-exclusive scenarios (e.g. WILL OCCUR vs WILL NOT OCCUR) that have probabilities p1 and p2 and `p1+p2 !-= 0`.
Scenarios like the above should have probabilities that sum to 1.

2 - Scenarios which are "complimentary" - e.g. WILL IT RAIN IN BERLIN IN 02.07.2024 and WILL IT RAIN IN BERLIN ON ANY DAY UNTIL 03.07.2024 - have probabilities p1 and p2 of happening, and p1 <= p2.

What I'm thinking here is having another agent (with another prompt) that only assigns probabilities to scenarios.

Input/feedback welcome.

**Comment by kongzii** [comment] 2024-07-01 11:43
Closing as duplicate of https://github.com/gnosis/prediction-market-agent/issues/108

But a note here that `SCENARIOS_WITH_PROBABILITIES` is not prompted to contain only mutually exclusive scenarios and I don't think it should be (see this comment https://github.com/gnosis/prediction-market-agent/issues/108#issuecomment-2082061567)

**Closed by kongzii** 2024-07-01 11:43 UTC
Labels: trader-agent
